# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'howtoplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Howto(object):

    def main(self):
        from main import Ui_Main
        print('main button clicked')
        self.main = QtWidgets.QMainWindow()
        self.Ui = Ui_Main()
        self.Ui.setupUi(self.main)
        self.main.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(688, 490)
        Form.setStyleSheet("*{\n"
"background-color: #f5b15d;\n"
"\n"
"}\n"
"\n"
"#gm_nm{\n"
"font:45px \"Marker Felt\";\n"
"color:#2a1f91;\n"
"\n"
"}")
        self.gm_nm = QtWidgets.QLabel(Form)
        self.gm_nm.setGeometry(QtCore.QRect(48, 50, 251, 51))
        self.gm_nm.setObjectName("gm_nm")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(68, 170, 191, 191))
        self.toolButton.setStyleSheet("border-image: url(:/Ghost/Sprites/logghost.png);")
        self.toolButton.setText("")
        self.toolButton.setIconSize(QtCore.QSize(100, 100))
        self.toolButton.setAutoRepeat(False)
        self.toolButton.setObjectName("toolButton")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(320, 30, 311, 421))
        self.frame.setStyleSheet("QFrame{\n"
"border:none;\n"
"background:#fdc47e;\n"
"}\n"
"\n"
"#howlbl{\n"
"color:#2a1f91;\n"
"font: 23pt \"Marker Felt\";\n"
"}\n"
"\n"
"QTextBrowser{\n"
"font: 24pt \"Marker Felt\";\n"
"color:#9b2929\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.toolButton_4 = QtWidgets.QToolButton(self.frame)
        self.toolButton_4.setGeometry(QtCore.QRect(250, 30, 61, 51))
        self.toolButton_4.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_4.setText("")
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.frame)
        self.toolButton_5.setGeometry(QtCore.QRect(220, -10, 61, 51))
        self.toolButton_5.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_5.setText("")
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_9 = QtWidgets.QToolButton(self.frame)
        self.toolButton_9.setGeometry(QtCore.QRect(300, 140, 61, 51))
        self.toolButton_9.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_9.setText("")
        self.toolButton_9.setObjectName("toolButton_9")
        self.toolButton_7 = QtWidgets.QToolButton(self.frame)
        self.toolButton_7.setGeometry(QtCore.QRect(180, -40, 61, 51))
        self.toolButton_7.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_7.setText("")
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtWidgets.QToolButton(self.frame)
        self.toolButton_8.setGeometry(QtCore.QRect(290, 110, 61, 51))
        self.toolButton_8.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_8.setText("")
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        self.toolButton_3.setGeometry(QtCore.QRect(280, -10, 61, 61))
        self.toolButton_3.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_3.setText("")
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_6 = QtWidgets.QToolButton(self.frame)
        self.toolButton_6.setGeometry(QtCore.QRect(280, 70, 61, 51))
        self.toolButton_6.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_6.setText("")
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_14 = QtWidgets.QToolButton(self.frame)
        self.toolButton_14.setGeometry(QtCore.QRect(36, 33, 41, 41))
        self.toolButton_14.setStyleSheet("border-image: url(:/mainicons/how.png);\n"
"background:transparent;")
        self.toolButton_14.setText("")
        self.toolButton_14.setIconSize(QtCore.QSize(100, 100))
        self.toolButton_14.setAutoRepeat(False)
        self.toolButton_14.setObjectName("toolButton_14")
        self.howlbl = QtWidgets.QLabel(self.frame)
        self.howlbl.setGeometry(QtCore.QRect(80, 40, 161, 31))
        self.howlbl.setObjectName("howlbl")
        self.howtext = QtWidgets.QTextBrowser(self.frame)
        self.howtext.setGeometry(QtCore.QRect(20, 120, 281, 281))
        font = QtGui.QFont()
        font.setFamily("Marker Felt")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.howtext.setFont(font)
        self.howtext.setStyleSheet("")
        self.howtext.setObjectName("howtext")
        self.toolButton_2 = QtWidgets.QToolButton(Form)
        self.toolButton_2.setGeometry(QtCore.QRect(10, 430, 51, 51))
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_2.setStyleSheet("border-image: url(:/main/Sprites/mainpage.png);")
        self.toolButton_2.setText("")
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_2.clicked.connect(self.main)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "HOW TO PLAY"))
        self.gm_nm.setText(_translate("Form", "GHOSTFIELD"))
        self.howlbl.setText(_translate("Form", "HOW TO PLAY?"))
        self.howtext.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Marker Felt\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">GHOSTFIELD is a single player computer game.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\"> The object of the game is to find all the empty squares in an area without encountering any mines. </span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">The numbers that appear when you click on the squares show the sum of the number of mines around the square.</span></p></body></html>"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Howto()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
