# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import subprocess
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):


    def scorepage(self):
        from scorepage import Ui_ScorePage
        print('scorepage button clicked')
        self.score = QtWidgets.QMainWindow()
        self.Ui = Ui_ScorePage()
        self.Ui.setupUi(self.score)
        self.score.show()

    def howto(self):
        from howtoplay import Ui_Howto
        print('scorepage button clicked')
        self.howto = QtWidgets.QMainWindow()
        self.Ui = Ui_Howto()
        self.Ui.setupUi(self.howto)
        self.howto.show()

    def startgame(self):
        from log import Ui_Log
        print('login button clicked')
        self.log = QtWidgets.QMainWindow()
        self.Ui = Ui_Log()
        self.Ui.setupUi(self.log)
        self.log.show()


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(688, 490)
        Form.setStyleSheet("*{\n"
"background-color: #f5b15d;\n"
"\n"
"}\n"
"\n"
"#gm_nm{\n"
"font:45px \"Marker Felt\";\n"
"color:#2a1f91;\n"
"\n"
"}")
        self.gm_nm = QtWidgets.QLabel(Form)
        self.gm_nm.setGeometry(QtCore.QRect(48, 50, 251, 51))
        self.gm_nm.setObjectName("gm_nm")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(68, 170, 191, 191))
        self.toolButton.setStyleSheet("border-image: url(:/Ghost/Sprites/logghost.png);\n"
"background:transparent;")
        self.toolButton.setText("")
        self.toolButton.setIconSize(QtCore.QSize(100, 100))
        self.toolButton.setAutoRepeat(False)
        self.toolButton.setObjectName("toolButton")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(320, 40, 311, 411))
        self.frame.setStyleSheet("QFrame{\n"
"border:none;\n"
"background:#fdc47e;\n"
"}\n"
"\n"
"#log_lbl{\n"
"color:#2a1f91;\n"
"font: 23pt \"Marker Felt\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"background:transparent;\n"
"border:none;\n"
"color:#5371fd;\n"
"border-bottom: 1px solid #858587;\n"
"text-align:center;\n"
"font: italic 15pt \"Marker Felt\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background: #3FA7E1;\n"
"color: white;\n"
"border-radius:15px;\n"
"    font: 15pt \"Marker Felt\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: white;\n"
"border-radius: 15px;\n"
"background: #0C8CD3;\n"
"cursor: point;\n"
"    font: 15pt \"Marker Felt\";\n"
"}\n"
"\n"
"QRadioButton{\n"
"color: #6577cd;\n"
"background: transparent;\n"
"font: 13pt \"Marker Felt\";\n"
"}\n"
"\n"
"#regbutton{\n"
"background: transparent;\n"
"color: #2a1f91;\n"
"font: 12pt \"Marker Felt\";\n"
"text-decoration: 2px underline;\n"
"}\n"
"#regbutton:hover{\n"
"background: transparent;\n"
"color: #756add;\n"
"font: 12pt \"Marker Felt\";\n"
"text-decoration: 2px underline;\n"
"}\n"
"#signlbl{\n"
"font: 12pt \"Marker Felt\";\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.toolButton_4 = QtWidgets.QToolButton(self.frame)
        self.toolButton_4.setGeometry(QtCore.QRect(250, 30, 61, 51))
        self.toolButton_4.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_4.setText("")
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.frame)
        self.toolButton_5.setGeometry(QtCore.QRect(230, -10, 61, 51))
        self.toolButton_5.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_5.setText("")
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_9 = QtWidgets.QToolButton(self.frame)
        self.toolButton_9.setGeometry(QtCore.QRect(300, 140, 61, 51))
        self.toolButton_9.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_9.setText("")
        self.toolButton_9.setObjectName("toolButton_9")
        self.toolButton_7 = QtWidgets.QToolButton(self.frame)
        self.toolButton_7.setGeometry(QtCore.QRect(190, -40, 61, 51))
        self.toolButton_7.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_7.setText("")
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtWidgets.QToolButton(self.frame)
        self.toolButton_8.setGeometry(QtCore.QRect(290, 110, 61, 51))
        self.toolButton_8.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_8.setText("")
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        self.toolButton_3.setGeometry(QtCore.QRect(280, -10, 61, 61))
        self.toolButton_3.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_3.setText("")
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_6 = QtWidgets.QToolButton(self.frame)
        self.toolButton_6.setGeometry(QtCore.QRect(280, 70, 61, 51))
        self.toolButton_6.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_6.setText("")
        self.toolButton_6.setObjectName("toolButton_6")
        self.mnstartbtn = QtWidgets.QPushButton(self.frame)
        self.mnstartbtn.setGeometry(QtCore.QRect(92, 111, 185, 51))
        self.mnstartbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mnstartbtn.setStyleSheet("#mnstartbtn{\n"
"background:#6267cb\n"
"}\n"
"#mnstartbtn:hover{\n"
"background:#7b7eb6\n"
"}\n"
"")
        self.mnstartbtn.setObjectName("mnstartbtn")
        self.mnstartbtn.clicked.connect(self.startgame)

        self.mnhowbtn = QtWidgets.QPushButton(self.frame)
        self.mnhowbtn.setGeometry(QtCore.QRect(92, 242, 185, 51))
        self.mnhowbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mnhowbtn.setStyleSheet("#mnhowbtn{\n"
"background:#6BdE6B\n"
"}\n"
"#mnhowbtn:hover{\n"
"background:#98DE98\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.mnhowbtn.setObjectName("mnhowbtn")
        self.mnhowbtn.clicked.connect(self.howto)
        self.mnscorebtn = QtWidgets.QPushButton(self.frame)
        self.mnscorebtn.setGeometry(QtCore.QRect(92, 177, 185, 51))
        self.mnscorebtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mnscorebtn.setStyleSheet("#mnscorebtn{\n"
                                      "background:#D74753\n"
                                      "\n"
                                      "}\n"
                                      "#mnscorebtn:hover{\n"
                                      "background:#E1616B\n"
                                      "\n"
                                      "}\n"
                                      "")
        self.mnscorebtn.setObjectName("mnscorebtn")
        self.mnscorebtn.clicked.connect(self.scorepage)
        self.toolButton_10 = QtWidgets.QToolButton(self.frame)
        self.toolButton_10.setGeometry(QtCore.QRect(32, 244, 51, 51))
        self.toolButton_10.setStyleSheet("border-image: url(:/mainicons/how.png);\n"
"background:transparent;")
        self.toolButton_10.setText("")
        self.toolButton_10.setObjectName("toolButton_10")
        self.toolButton_11 = QtWidgets.QToolButton(self.frame)
        self.toolButton_11.setGeometry(QtCore.QRect(32, 110, 51, 51))
        self.toolButton_11.setStyleSheet("border-image: url(:/mainicons/Sprites/gamebasla.png);\n"
"background:transparent;")
        self.toolButton_11.setText("")
        self.toolButton_11.setObjectName("toolButton_11")
        self.log_lbl = QtWidgets.QLabel(self.frame)
        self.log_lbl.setGeometry(QtCore.QRect(120, 30, 121, 31))
        self.log_lbl.setObjectName("log_lbl")
        self.toolButton_14 = QtWidgets.QToolButton(self.frame)
        self.toolButton_14.setGeometry(QtCore.QRect(75, 23, 43, 43))
        self.toolButton_14.setStyleSheet("border-image: url(:/main/Sprites/mainpage.png);\n"
"background:transparent;")
        self.toolButton_14.setText("")
        self.toolButton_14.setIconSize(QtCore.QSize(120, 120))
        self.toolButton_14.setAutoRepeat(False)
        self.toolButton_14.setObjectName("toolButton_14")
        self.toolButton_15 = QtWidgets.QToolButton(self.frame)
        self.toolButton_15.setGeometry(QtCore.QRect(32, 178, 51, 51))
        self.toolButton_15.setStyleSheet("border-image: url(:/mainicons/Sprites/score.png);\n"
"background:transparent;")
        self.toolButton_15.setText("")
        self.toolButton_15.setObjectName("toolButton_15")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MAIN PAGE"))
        self.gm_nm.setText(_translate("Form", "GHOSTFIELD"))
        self.mnstartbtn.setText(_translate("Form", "START GAME"))
        self.mnhowbtn.setText(_translate("Form", "HOW TO PLAY?"))
        self.log_lbl.setText(_translate("Form", "MAIN PAGE"))
        self.mnscorebtn.setText(_translate("Form", "SCORE PAGE"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Main()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
