# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scorepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScorePage(object):

    def main(self):
        from main import Ui_Main
        print('main button clicked')
        self.main = QtWidgets.QMainWindow()
        self.Ui = Ui_Main()
        self.Ui.setupUi(self.main)
        self.main.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(688, 490)
        Form.setStyleSheet("*{\n"
"background-color: #f5b15d;\n"
"\n"
"}\n"
"\n"
"#gm_nm{\n"
"font:45px \"Marker Felt\";\n"
"color:#2a1f91;\n"
"\n"
"}")
        self.gm_nm = QtWidgets.QLabel(Form)
        self.gm_nm.setGeometry(QtCore.QRect(48, 50, 251, 51))
        self.gm_nm.setObjectName("gm_nm")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(68, 170, 191, 191))
        self.toolButton.setStyleSheet("border-image: url(:/Ghost/Sprites/logghost.png);")
        self.toolButton.setText("")
        self.toolButton.setIconSize(QtCore.QSize(100, 100))
        self.toolButton.setAutoRepeat(False)
        self.toolButton.setObjectName("toolButton")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(320, 30, 311, 421))
        self.frame.setStyleSheet("QFrame{\n"
"border:none;\n"
"background:#fdc47e;\n"
"}\n"
"\n"
"#howlbl{\n"
"color:#2a1f91;\n"
"font: 23pt \"Marker Felt\";\n"
"}\n"
"\n"
"QTextBrowser{\n"
"font: 24pt \"Marker Felt\";\n"
"color:#9b2929\n"
"}\n"
"QTableWidget{\n"
"\n"
"background:\n"
"color:white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
#         self.toolButton_4 = QtWidgets.QToolButton(self.frame)
#         self.toolButton_4.setGeometry(QtCore.QRect(260, 30, 61, 51))
#         self.toolButton_4.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
# "background:transparent;")
#         self.toolButton_4.setText("")
#         self.toolButton_4.setObjectName("toolButton_4")
#         self.toolButton_5 = QtWidgets.QToolButton(self.frame)
#         self.toolButton_5.setGeometry(QtCore.QRect(220, -10, 61, 51))
#         self.toolButton_5.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
# "background:transparent;")
#         self.toolButton_5.setText("")
#         self.toolButton_5.setObjectName("toolButton_5")
#         self.toolButton_9 = QtWidgets.QToolButton(self.frame)
#         self.toolButton_9.setGeometry(QtCore.QRect(300, 140, 61, 51))
#         self.toolButton_9.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
# "background:transparent;")
#         self.toolButton_9.setText("")
#         self.toolButton_9.setObjectName("toolButton_9")
#         self.toolButton_7 = QtWidgets.QToolButton(self.frame)
#         self.toolButton_7.setGeometry(QtCore.QRect(180, -40, 61, 51))
#         self.toolButton_7.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
# "background:transparent;")
#         self.toolButton_7.setText("")
#         self.toolButton_7.setObjectName("toolButton_7")
#         self.toolButton_8 = QtWidgets.QToolButton(self.frame)
#         self.toolButton_8.setGeometry(QtCore.QRect(290, 110, 61, 51))
#         self.toolButton_8.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
# "background:transparent;")
#         self.toolButton_8.setText("")
#         self.toolButton_8.setObjectName("toolButton_8")
#         self.toolButton_3 = QtWidgets.QToolButton(self.frame)
#         self.toolButton_3.setGeometry(QtCore.QRect(280, -10, 61, 61))
#         self.toolButton_3.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
# "background:transparent;")
#         self.toolButton_3.setText("")
#         self.toolButton_3.setObjectName("toolButton_3")
#         self.toolButton_6 = QtWidgets.QToolButton(self.frame)
#         self.toolButton_6.setGeometry(QtCore.QRect(280, 70, 61, 51))
#         self.toolButton_6.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
# "background:transparent;")
#         self.toolButton_6.setText("")
#         self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_14 = QtWidgets.QToolButton(self.frame)
        self.toolButton_14.setGeometry(QtCore.QRect(90, 17, 31, 31))
        self.toolButton_14.setStyleSheet("border-image: url(:/mainicons/won.png);\n"
"background:transparent;")
        self.toolButton_14.setText("")
        self.toolButton_14.setIconSize(QtCore.QSize(100, 100))
        self.toolButton_14.setAutoRepeat(False)
        self.toolButton_14.setObjectName("toolButton_14")
        self.howlbl = QtWidgets.QLabel(self.frame)
        self.howlbl.setGeometry(QtCore.QRect(130, 23, 81, 31))
        self.howlbl.setObjectName("howlbl")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(50, 70, 225, 323))
        self.tableWidget.setStyleSheet("*{\n"
"font: 13pt \"Marker Felt\";\n"
"color:black;\n"
"background:#fba842\n"
"}\n"
"\n"
"QTableWidget{\n"
"font: 13pt \"Marker Felt\";\n"
"color:black;\n"
"background:#fbbc6e\n"
"\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.toolButton_2 = QtWidgets.QToolButton(Form)
        self.toolButton_2.setGeometry(QtCore.QRect(10, 430, 51, 51))
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_2.setStyleSheet("border-image: url(:/main/Sprites/mainpage.png);")
        self.toolButton_2.setText("")
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_2.clicked.connect(self.main)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.con()
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SCORES"))
        self.gm_nm.setText(_translate("Form", "GHOSTFIELD"))
        self.howlbl.setText(_translate("Form", "SCORES"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "USERNAME"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "SCORE"))
        import source_rc

    def con(self):
            conn = sqlite3.connect('database.db')
            query = ''' SELECT username, score FROM gamers order by score desc '''
            result = conn.execute(query)
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                    self.tableWidget.insertRow(row_number)
                    for column_number, column_data in enumerate(row_data):
                            self.tableWidget.setItem(row_number, column_number,
                                                     QtWidgets.QTableWidgetItem(str(column_data)))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_ScorePage()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

