# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sqlite3

class Ui_Sign(object):

    def sign(self):
        from log import Ui_Log
        print('login button clicked')
        name=self.nmLine.text()
        surname=self.surnmLine.text()
        username = self.userLine.text()
        mail = self.mailLine.text()
        password = self.passLine.text()
        print(name)
        print(surname)
        print(name)
        print(mail)
        print(password)

        connection = sqlite3.connect('database.db')
        print('connexion done')

        if (self.nmLine.text()) != "" and (self.surnmLine.text()) != "" and (self.userLine.text()) != "" and (self.mailLine.text()) != "" and (self.passLine.text()) != "":
            connection.execute(''' INSERT INTO gamers(name,surname,username,mail,password) VALUES(?,?,?,?,?)''',(name, surname,username,mail,password))
            print("kayıt olundu")
            connection.commit()
            self.nmLine.setText("")
            self.surnmLine.setText("")
            self.userLine.setText("")
            self.mailLine.setText("")
            self.passLine.setText("")
            self.wronglbl.setText("")

            self.log = QtWidgets.QMainWindow()
            self.Ui = Ui_Log()
            self.Ui.setupUi(self.log)
            self.log.show()

        else:
            self.wronglbl.setText("*Please Fill in the Fields")

    def login(self):
        from log import Ui_Log
        print('login button clicked')

        self.log = QtWidgets.QMainWindow()
        self.Ui = Ui_Log()
        self.Ui.setupUi(self.log)
        self.log.show()

    def main(self):
        from main import Ui_Main
        print('main button clicked')

        self.main = QtWidgets.QMainWindow()
        self.Ui = Ui_Main()
        self.Ui.setupUi(self.main)
        self.main.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(688, 490)
        Form.setStyleSheet("*{\n"
"background-color: #f5b15d;\n"
"\n"
"}\n"
"\n"
"#gm_nm{\n"
"font:45px \"Marker Felt\";\n"
"color:#2a1f91;\n"
"\n"
"}")
        self.gm_nm = QtWidgets.QLabel(Form)
        self.gm_nm.setGeometry(QtCore.QRect(48, 50, 251, 51))
        self.gm_nm.setObjectName("gm_nm")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(68, 170, 191, 191))
        self.toolButton.setStyleSheet("border-image: url(:/Ghost/Sprites/logghost.png);")
        self.toolButton.setText("")
        self.toolButton.setIconSize(QtCore.QSize(100, 100))
        self.toolButton.setAutoRepeat(False)
        self.toolButton.setObjectName("toolButton")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(320, 30, 311, 421))
        self.frame.setStyleSheet("QFrame{\n"
"border:none;\n"
"background:#fdc47e;\n"
"}\n"
"\n"
"#log_lbl{\n"
"color:#2a1f91;\n"
"font: 23pt \"Marker Felt\";\n"
"}\n"
"\n"
"#wronglbl{\n"
"color:#2a1f91;\n"
"font: 14pt \"Marker Felt\";\n"
"}\n"
"\n"    
"QLineEdit{\n"
"background:transparent;\n"
"border:none;\n"
"color:#5371fd;\n"
"border-bottom: 1px solid #858587;\n"
"text-align:center;\n"
"    font: italic 15pt \"Marker Felt\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background: #2a1f91;\n"
"color: white;\n"
"border-radius:15px;\n"
"    font: 15pt \"Marker Felt\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: white;\n"
"border-radius: 15px;\n"
"background: #756add;\n"
"cursor: point;\n"
"    font: 15pt \"Marker Felt\";\n"
"}\n"
"\n"
"QRadioButton{\n"
"color: #6577cd;\n"
"background: transparent;\n"
"font: 13pt \"Marker Felt\";\n"
"}\n"
"\n"
"#regbutton{\n"
"background: transparent;\n"
"color: #2a1f91;\n"
"font: 12pt \"Marker Felt\";\n"
"text-decoration: 2px underline;\n"
"}\n"
"#regbutton:hover{\n"
"background: transparent;\n"
"color: #756add;\n"
"font: 12pt \"Marker Felt\";\n"
"text-decoration: 2px underline;\n"
"}\n"
"#signlbl{\n"
"font: 12pt \"Marker Felt\";\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.nmLine = QtWidgets.QLineEdit(self.frame)
        self.nmLine.setGeometry(QtCore.QRect(50, 70, 211, 31))
        self.nmLine.setObjectName("nmLine")
        self.surnmLine = QtWidgets.QLineEdit(self.frame)
        self.surnmLine.setGeometry(QtCore.QRect(50, 110, 211, 31))
        self.surnmLine.setObjectName("surnmLine")
        self.userLine = QtWidgets.QLineEdit(self.frame)
        self.userLine.setGeometry(QtCore.QRect(50, 150, 211, 31))
        self.userLine.setObjectName("userLine")
        self.mailLine = QtWidgets.QLineEdit(self.frame)
        self.mailLine.setGeometry(QtCore.QRect(50, 190, 211, 31))
        self.mailLine.setObjectName("mailLine")
        self.passLine = QtWidgets.QLineEdit(self.frame)
        self.passLine.setGeometry(QtCore.QRect(50, 230, 211, 31))
        self.passLine.setObjectName("passLine")
        self.passLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.logButton = QtWidgets.QPushButton(self.frame)
        self.logButton.setGeometry(QtCore.QRect(110, 300, 113, 32))
        self.logButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logButton.setObjectName("logButton")
        self.logButton.clicked.connect(self.sign)
        self.log_lbl = QtWidgets.QLabel(self.frame)
        self.log_lbl.setGeometry(QtCore.QRect(120, 20, 81, 31))
        self.log_lbl.setObjectName("log_lbl")
        self.signlbl = QtWidgets.QLabel(self.frame)
        self.signlbl.setGeometry(QtCore.QRect(90, 360, 121, 16))
        self.signlbl.setObjectName("signlbl")
        self.regbutton = QtWidgets.QPushButton(self.frame)
        self.regbutton.setGeometry(QtCore.QRect(200, 360, 41, 16))
        self.regbutton.setObjectName("regbutton")
        self.regbutton.clicked.connect(self.login)
        self.regbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_4 = QtWidgets.QToolButton(self.frame)
        self.toolButton_4.setGeometry(QtCore.QRect(250, 30, 61, 51))
        self.toolButton_4.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_4.setText("")
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.frame)
        self.toolButton_5.setGeometry(QtCore.QRect(220, -10, 61, 51))
        self.toolButton_5.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_5.setText("")
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_9 = QtWidgets.QToolButton(self.frame)
        self.toolButton_9.setGeometry(QtCore.QRect(300, 140, 61, 51))
        self.toolButton_9.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_9.setText("")
        self.toolButton_9.setObjectName("toolButton_9")
        self.toolButton_7 = QtWidgets.QToolButton(self.frame)
        self.toolButton_7.setGeometry(QtCore.QRect(180, -40, 61, 51))
        self.toolButton_7.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_7.setText("")
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtWidgets.QToolButton(self.frame)
        self.toolButton_8.setGeometry(QtCore.QRect(290, 110, 61, 51))
        self.toolButton_8.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_8.setText("")
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        self.toolButton_3.setGeometry(QtCore.QRect(280, -10, 61, 61))
        self.toolButton_3.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_3.setText("")
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_6 = QtWidgets.QToolButton(self.frame)
        self.toolButton_6.setGeometry(QtCore.QRect(280, 70, 61, 51))
        self.toolButton_6.setStyleSheet("border-image: url(:/prt/icons8-party-64.png);\n"
"background:transparent;")
        self.toolButton_6.setText("")
        self.toolButton_6.setObjectName("toolButton_6")
        self.mainbtn = QtWidgets.QToolButton(Form)
        self.mainbtn.setGeometry(QtCore.QRect(10, 430, 51, 51))
        self.mainbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mainbtn.setStyleSheet("border-image: url(:/main/Sprites/mainpage.png);")
        self.mainbtn.setText("")
        self.mainbtn.setObjectName("mainbtn")
        self.mainbtn.clicked.connect(self.main)
        self.wronglbl = QtWidgets.QLabel(self.frame)
        self.wronglbl.setGeometry(QtCore.QRect(90, 267, 211, 31))
        self.wronglbl.setObjectName("wronglbl")

        self.toolButton_14 = QtWidgets.QToolButton(self.frame)
        self.toolButton_14.setGeometry(QtCore.QRect(80, 17, 31, 31))
        self.toolButton_14.setStyleSheet("border-image: url(:/Ghost/Sprites/logghost.png);\n"
                                         "background:transparent;")
        self.toolButton_14.setText("")
        self.toolButton_14.setIconSize(QtCore.QSize(100, 100))
        self.toolButton_14.setAutoRepeat(False)
        self.toolButton_14.setObjectName("toolButton_14")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SIGN IN"))
        self.gm_nm.setText(_translate("Form", "GHOSTFIELD"))
        self.surnmLine.setPlaceholderText(_translate("Form", "SURNAME"))
        self.mailLine.setPlaceholderText(_translate("Form", "E-MAIL"))
        self.passLine.setPlaceholderText(_translate("Form", "PASSWORD"))
        self.nmLine.setPlaceholderText(_translate("Form", "NAME"))
        self.logButton.setText(_translate("Form", "SIGN IN"))
        self.log_lbl.setText(_translate("Form", "SIGN IN"))
        self.signlbl.setText(_translate("Form", "Do you have account?"))
        self.regbutton.setText(_translate("Form", "Log in"))
        self.userLine.setPlaceholderText(_translate("Form", "USERNAME"))
        self.wronglbl.setText(_translate("Form", " "))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Sign()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
